CREATE TABLE `detalle_de_venta` (
  `COD_VENTA` INTEGER(11) NOT NULL,
  `SUBTOTAL_PRODUCTO` INTEGER(11) DEFAULT NULL,
  `CANTIDAD_PRODUCTO` INTEGER(11) DEFAULT NULL,
  PRIMARY KEY (`COD_VENTA`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_5` FOREIGN KEY (`COD_VENTA`) REFERENCES `venta` (`COD_VENTA`)
) ENGINE=InnoDB
CHARACTER SET 'latin1' COLLATE 'latin1_swedish_ci'
;