CREATE TABLE `forma_de_pago` (
  `COD_FORMA_PAGO` INTEGER(11) NOT NULL,
  `EFECTIVO` VARCHAR(10) COLLATE latin1_swedish_ci DEFAULT NULL,
  `TAJETA_CREDITO` VARCHAR(10) COLLATE latin1_swedish_ci DEFAULT NULL,
  PRIMARY KEY (`COD_FORMA_PAGO`) USING BTREE
) ENGINE=InnoDB
CHARACTER SET 'latin1' COLLATE 'latin1_swedish_ci'
;