
CREATE TABLE `producto` (
  `COD_PRODUCTO` INTEGER(11) NOT NULL,
  `COD_TIPO_PRODUCTO` INTEGER(11) DEFAULT NULL,
  `NOMBRE_PRODUCTO` VARCHAR(50) COLLATE latin1_swedish_ci DEFAULT NULL,
  `CATIDAD_PRODUCTO` INTEGER(11) DEFAULT NULL,
  `DESCUENTO_PRODUCTO` VARCHAR(30) COLLATE latin1_swedish_ci DEFAULT NULL,
  `PRECIO_PRODCUTO` DECIMAL(10,0) DEFAULT NULL,
  PRIMARY KEY (`COD_PRODUCTO`) USING BTREE,
  KEY `FK_RELATIONSHIP_4` (`COD_TIPO_PRODUCTO`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_4` FOREIGN KEY (`COD_TIPO_PRODUCTO`) REFERENCES `tipo_de_producto` (`COD_TIPO_PRODUCTO`)
) ENGINE=InnoDB
CHARACTER SET 'latin1' COLLATE 'latin1_swedish_ci'
;