
CREATE TABLE `tipo_de_producto` (
  `COD_TIPO_PRODUCTO` INTEGER(11) NOT NULL,
  `NOMBRE_TIPO_PRODUCTO` VARCHAR(30) COLLATE latin1_swedish_ci DEFAULT NULL,
  PRIMARY KEY (`COD_TIPO_PRODUCTO`) USING BTREE
) ENGINE=InnoDB
CHARACTER SET 'latin1' COLLATE 'latin1_swedish_ci'
;
