
CREATE TABLE `venta` (
  `COD_VENTA` INTEGER(11) NOT NULL,
  `DET_COD_VENTA` INTEGER(11) DEFAULT NULL,
  `COD_FORMA_PAGO` INTEGER(11) DEFAULT NULL,
  `COD_PRODUCTO` INTEGER(11) DEFAULT NULL,
  `FECHA_VENTA` DATE DEFAULT NULL,
  `TOTAL_VENTA` DECIMAL(10,0) DEFAULT NULL,
  PRIMARY KEY (`COD_VENTA`) USING BTREE,
  KEY `FK_RELATIONSHIP_1` (`DET_COD_VENTA`) USING BTREE,
  KEY `FK_RELATIONSHIP_2` (`COD_FORMA_PAGO`) USING BTREE,
  KEY `FK_RELATIONSHIP_3` (`COD_PRODUCTO`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_1` FOREIGN KEY (`DET_COD_VENTA`) REFERENCES `detalle_de_venta` (`COD_VENTA`),
  CONSTRAINT `FK_RELATIONSHIP_2` FOREIGN KEY (`COD_FORMA_PAGO`) REFERENCES `forma_de_pago` (`COD_FORMA_PAGO`),
  CONSTRAINT `FK_RELATIONSHIP_3` FOREIGN KEY (`COD_PRODUCTO`) REFERENCES `producto` (`COD_PRODUCTO`)
) ENGINE=InnoDB
CHARACTER SET 'latin1' COLLATE 'latin1_swedish_ci'
;